### ISSUE TITLE
New feature: Quick Filters (like in standard boards)

### ISSUE THREAD

**Issue by edtro** [edtro/EdTro.AzureDevOps.Extensions.querybasedboards#1]

**Comment by edtro** [comment]
First screenshot:
![image](https://user-images.githubusercontent.com/27762373/98333206-8649bb80-2000-11eb-8e31-31720f582d20.png)

**Comment by jannikajbrink** [comment]
I'm not sure if this is the right place to leave comments about a specific feature but I did not find the suggested Q and A section.
I think this a great feature and it's a deal breaker to use the extension. I have some issues using the feature with my "one-hop" query, displaying user storys and tasks though:
1. The filter "Assigned To" only contains users assigned to the user stories, not the tasks. There is also no way to manually enter a user only assigned to tasks.
2. When selecting a user in the filter, I also think it only filters the tasks, not the user stories like the standard task board which filters both user stories and tasks 
3. It would be nice if the User Stories (parents) not matching the filter would be collapsed as they are in the standard task board

**Comment by edtro** [comment]
Hi @jannikajbrink 
Thanks for replying... and yes you are in the correct place :-)

I will try to answer all of your questions, as good as I can...

> 1. The filter "Assigned To" only contains users assigned to the user stories, not the tasks. There is also no way to manually enter a user only assigned to tasks.

This should not be the case. I think you have stumbled upon a real bug here.... and I think I already have found the cause of it. I am in the middle of rounding up a release, so I try to include the solution for this.

> 2. When selecting a user in the filter, I think it only filters the tasks, not the user stories like the standard task board which filters both user stories and tasks

This indeed is the designed behaviour. There is a big difference with the general boards and my extension. Within the boards, the filters are the only way to adjust the query. While my extension is based on query resultset, so you can adjust the query itself, so the results are reflected within the Query Based Board. Hence the name 'Quick filters'... my goal is to allow quickly filter on certain fields, while you are in e.g. a sprintmeeting. So filtering just on tasks within the Taskboard, makes more sense to me.  

> 3. It would be nice if the User Stories (parents) not matching the filter would collapse as they do in the standard task board

Agreed, but maybe I am able to combine this with one of my new features. I am adding two new quickfilters just for the Taskboard... 'Parent has children' and 'Parent state'. I am not sure if I am able to do this, for the next release however.

Kr
Edward

**Comment by edtro** [comment]
Hi,

The first item is resolved and will be delivered within the next release.

For the third item, I was able to squeeze in a last minute minor change to a new feature I am introducing... here is a screenshot:
![image](https://user-images.githubusercontent.com/27762373/102709114-96171980-42a7-11eb-8e89-fea899a4509f.png)


With this new filteroption, you are now able to combine it with the existing filteroptions... so you will get what you are expecting.

I will start the final testing prior to the release very soon...

Kr
Edward
