### ISSUE TITLE
New feature: allow to setup of what fields that should be displayed on the cards

### ISSUE THREAD

**Issue by edtro** [edtro/EdTro.AzureDevOps.Extensions.querybasedboards#12]

**Comment by w0nders** [comment]
Do you have update for this feature?

**Comment by edtro** [comment]
@w0nders Unfortunately not... I am still working at an other feature (see #7). But other priorities (at work and private) don't allow me to spend as mutch time at this new feature, as  I want to. So other features like this one will remain on the todolist for the moment. Hoping to get back at it very soon. Kr. Edward

**Comment by edtro** [comment]
First screenshot:
![image](https://user-images.githubusercontent.com/27762373/98333063-3c60d580-2000-11eb-846b-e04c669e33d6.png)

**Comment by vincenormand** [comment]
Very nice ! Keep up the great job !

**Comment by Lazys** [comment]
Uhh please give it to us as preview ASAP, we need the field "Team project" so much :))

**Comment by edtro** [comment]
Released in v0.20326 as PREVIEW
