### ISSUE TITLE
After creating an private query the QBB doesn't work for others

### ISSUE THREAD

**Issue by zmartaz** [edtro/EdTro.AzureDevOps.Extensions.querybasedboards#15]
Hello!
So the situation is that while we work with shared querys on our Azure DevOps everything works fine and there are no problems. But if one creates a private query and selects to show it as board, then the query based board shows for others only the "Whoops... Something went wrong while loading the configuration page.". For the one who created the private query it still works fine. 
If then another person creates also a private query and selects to show it as board, then the query based board extension doesn't work for anyone anymore. 
Could this bes somehow fixed?

**Comment by edtro** [comment]
Dear zmartaz,
I will be looking into this...
Keep you posted!

(can you please provide me with some detailled information... like what is displayed within the console.log, thanks in advance)
Kr
Edward

**Comment by edtro** [comment]
I think that I have found the source of the issue within the configuration page. I will be creating a hotfix release soon.

**Comment by edtro** [comment]
Hi, I have created a new release to resolve this problem (this is now available on the marketplace). Within the Configuration Hub the loading error should not appear any more. I have added a checkbox called 'View all queries'... this will enable you, to see configurations of all private queries (for all users), however details cannot be loaded. I also have added extra details (like path and wiql) to give some extra guidance.  

Please let me know it this resolved your problem.

Kr
Edward

**Comment by edtro** [comment]
Solved in v0.20134

**Comment by zmartaz** [comment]
Thanks, everything working fine now!

**Comment by edtro** [comment]
Thank you for your feedback! 
Highly appreciated.
Kr
Edward
