### ISSUE TITLE
Possibility to show team on the work item card

### ISSUE THREAD

**Issue by Lazys** [edtro/EdTro.AzureDevOps.Extensions.querybasedboards#18]
It would be nice if we could see Team or Area on the work item card - we mostly use queries with option "query across projects" so this is very important for us.

**Comment by edtro** [comment]
Hi, thanks for the feedback.
I already have raised an issue for this... see ref: #12 
So yes, I agree, that this would be great to have! Especially for this.
Kr
Edward

**Comment by Lazys** [comment]
Great! Thanks :)
