### ISSUE TITLE
Collapsible columns behavior is not clear

### ISSUE THREAD

**Issue by vernazza** [edtro/EdTro.AzureDevOps.Extensions.querybasedboards#20]
Some of the columns have an arrow that allow them to be collapsed.
I thought it was the "isBacklog" parameter in the column definition to set that, but it's something else (or it is and it isn't properly working).
So: it's some hidden configuration, it's a bug or it's something else?

**Comment by edtro** [comment]
Hi,
Like I have mentioned in the config.md, I did not have the time to create proper documentation, sorry about that.

How it should be working:
* no configuration: it is based on the Category of the State (this is retrieved from the REST api)... 'Proposed' and 'Completed' are considered 'backlog' columns and can be collapsed.
* within the configuration: the Column should have the property "isBacklog" been set to 'True'.

(and I have no leads to assume that there is something broken here, so based on my current information I have to say, that there is no bug here)

Within the Config.md  I have mentioned some tips, that you could use, when you are trying using the configurations.  

But keep in mind... setting up the Columns is just the first feature that I have released, there are more to come. Maybe some design considerations will become more clearly when the other features are also shipped. But this can take some time.

I hope this helps.
Kr
Edward

**Comment by edtro** [comment]
Hi,
I have had the time to investigate this a little bit further. And it seems that the configuration is ignored completely. So it only looks at the Category of the State at the moment. Will try to fix this.

Thanks for reporting this.

Kr
Edward

**Comment by edtro** [comment]
Hi, I have managed to solve this issue... but unfortunately it has to wait until the next release. Currently I am  working on a couple of new features and I am hoping to be able to release these in the near future.  

I will report back on this issue, when it is released.

Kr
Edward

**Comment by edtro** [comment]
Is solved within v0.20305.3 that is just released.
