### ISSUE TITLE
"TeamProjectSettings hub" ?

### ISSUE THREAD

**Issue by StingyJack** [edtro/EdTro.AzureDevOps.Extensions.querybasedboards#21]
[this page ](https://github.com/edtro/EdTro.AzureDevOps.Extensions.querybasedboards/blob/master/public/config.md)  refers to a team project settings hub. I googled for this and did not find anything for Azure DevOps. Where would one locate this hub? Is there a different name for it?

**Comment by edtro** [comment]
Hi,

Here you go: https://docs.microsoft.com/en-us/azure/devops/extend/reference/targets/overview?view=azure-devops

Look for: Project settings
This is: ms.vss-web.project-admin-hub-group

Kr
Edward
