### ISSUE TITLE
New Feature: Parent on the work item card

### ISSUE THREAD

**Issue by Dilergore** [edtro/EdTro.AzureDevOps.Extensions.querybasedboards#32]
Hi,

While it is true it is possible to use the fields to configure the parent it will only display as non-clickable item number.

I would like this to work as a link with the proper item name like on the built-in board:
![image](https://user-images.githubusercontent.com/14315890/103757040-7c4c3500-5010-11eb-8f7a-f894a455e0dc.png)

Thanks!

**Comment by edtro** [comment]
Hi @Dilergore,
This is a great point. Didn't think of it... so I will be looking into this.

**Comment by edtro** [comment]
For the record... it is just showing this:
![image](https://user-images.githubusercontent.com/27762373/103773175-f1c4ff00-502a-11eb-8372-669fcf046d9e.png)

**Comment by edtro** [comment]
Solved in 0.21059
