### ISSUE TITLE
New Feature: Do not show items collapsible without subtasks

### ISSUE THREAD

**Issue by Dilergore** [edtro/EdTro.AzureDevOps.Extensions.querybasedboards#33]
Hi,

Currently with a two-level query all the parent level tasks are showing as collapsible:

![image](https://user-images.githubusercontent.com/14315890/103757345-f2509c00-5010-11eb-8b66-55e5f86cf4fd.png)

It would be good to have such tasks just on the board in the correct column based on their states like:
![image](https://user-images.githubusercontent.com/14315890/103757523-2cba3900-5011-11eb-84b3-f22c441a7987.png)

Thanks!

**Comment by edtro** [comment]
Hi @Dilergore,
Thank you for your feedback. Highly appreciated!
As you are requesting here, is not the way it is designed... it should work like the taskboard, so you will have stories as the parent level and the task as the child level (you can also use features with stories etc). 

So unfortunately, I have no plans to change this.

Kr
Edward
