### ISSUE TITLE
New Feature: User Filtering to only show relevant

### ISSUE THREAD

**Issue by Dilergore** [edtro/EdTro.AzureDevOps.Extensions.querybasedboards#34]
Hi,

Currently if you filter a board with a two level query to a certain user it will display all the first level categories no matter the user does not have it assigned:
![image](https://user-images.githubusercontent.com/14315890/103758447-82dbac00-5012-11eb-829a-a96319322a42.png)

It would be good to show only the relevant categories. It would only make sense to display them if the user is having subtasks in the Story / Feature. This would enable intra-story collaboration by seeing only the relevant work item categories and subtasks on the board when filtering.

This is somewhat connected to my other ticket:
https://github.com/edtro/EdTro.AzureDevOps.Extensions.querybasedboards/issues/33

Thanks!

**Comment by edtro** [comment]
Hi @Dilergore , 
You can achieve by also using the 'parent has children' filter when you are using the filter on the assigned to. Just select 'yes' within this filter option. 

Is this helpfull?

I think I will look into setting the 'Parent has children' filter automatically when you set the 'Assigned To' filter.
But I will have to investigate this further.

Kr
Edward

**Comment by Dilergore** [comment]
Hey,

More or less. Let me show you what I'm trying to put together using this and the other issue you closed (#33 ). We were using Jira so far where we had Epics, Stories, Issues, Spikes, Sub-Tasks. In hierarchy Issues/Spikes could not contain any subtasks; that was unique to Stories.

We had a single board where we were able to move all the tasks on all levels like this:
![image](https://user-images.githubusercontent.com/14315890/103771578-46b34600-5028-11eb-9687-addb44c04117.png)

This is a board which lets us to move both task levels (Requirement and Iteration with the DevOps terminology) with some intelligent grouping for clarity. Is this something I could do today / could you do something / do you have plans to make this available?

**Comment by edtro** [comment]
Hi @Dilergore ,
I understand what you trying to do.
But unfortunately this is not possible within my extension. 

However it is very interesting, I am not planning to implement something like this within the near future. 
Am just alone and doing this within my free spare time.

Kr
Edward

**Comment by Dilergore** [comment]
@edtro - Thank You for your response. My biggest problem is that it happens regularly that a story is being worked on by multiple people in the team. Currently there is no proper view to filter to a certain person and see the subtasks assigned unless the user is having the story assigned...

The problem might be how we organize our daily stand-ups: we usually go person by person and not task by task. We might want to change this to overcome this limitation.

**Comment by Dilergore** [comment]
So just as a feedback and if someone tries to do something similar:

I was able to more or less fulfill my requirements by doing the following changes:

I changed the 'Spike' and the 'Issue' to a lower level (from Requirement to the Iteration backlog):
![image](https://user-images.githubusercontent.com/14315890/103857696-3f874900-50b7-11eb-802d-9fce4705840e.png)

With this change my Taskboard looks close to what I showed before:
![image](https://user-images.githubusercontent.com/14315890/103858284-55493e00-50b8-11eb-858d-b529257255c2.png)

- With this approach I can see the Issues / Spikes (/ Bugs) on the board properly and not as a category
- Sub-Tasks can be moved properly not like on the built-in board where it is only checkable
- I can filter for certain users
- If the sub-tasks are distributed between multiple users the Story is still showing no matter the user we are filtering for is not owning it

Ofc it is not perfect because:
- Now you can add Spikes and Issues as sub-tasks to Stories which should not happen
- For Planning I needed to set-up a shared query because the built-in backlog is not showing Iteration level items...

 Along with this to further tune the behavior I created two Logic Apps in Azure:
- Triggering for Sub-Task creation and copies the Assigned To and the Tags to the Sub-Task
- Triggering for Sub-Task modification and copies the Tags from the parent to the Sub-Task

**Comment by edtro** [comment]
Nice one!

Just noticed that you are using the Scrum template with the PBI's but you have disabled this and created the custom 'Stories'. The Agile template has got the 'User Stories' by default. 

Kr
Edward
