### ISSUE TITLE
BUG: Line breaks not working properly for long strings without spaces in title

### ISSUE THREAD

**Issue by bewalterBL** [edtro/EdTro.AzureDevOps.Extensions.querybasedboards#35]
When the title contains long strings without spaces the wrapping of the text seems not to work properly for the board cards. As can be seen on the screenshots the text exceeds the boarders of the card.

![image](https://user-images.githubusercontent.com/75365667/103880879-feecf700-50d9-11eb-9ddc-93f4af437d9d.png)
![image](https://user-images.githubusercontent.com/75365667/103881271-833f7a00-50da-11eb-9045-60ea9ffa1064.png)

**Comment by edtro** [comment]
Hi @bewalterBL ,
I will look into it. Thanks for reporting this! I did not notice it before.
Kr
Edward

**Comment by bewalterBL** [comment]
Thank you for the quick response. I am glad to help to make it an even better extension. 
Best Bernhard

**Comment by edtro** [comment]
Solved in 0.21059
