### ISSUE TITLE
Possibility to create a Backlog based on Query

### ISSUE THREAD

**Issue by harleyquinn39** [edtro/EdTro.AzureDevOps.Extensions.querybasedboards#42]
I really like this extension and its functionality of visualizing dependencies and searching across projects. Do you think it will be (maybe already is) a possibility to create a backlog from the query?

I would like to use "Add a rollup column" for a backlog based on the query created from items from multiple projects.

**Comment by edtro** [comment]
@harleyquinn39 
Dear,
Yes, this is a great idea. If someone would build an extension with this feature, I would probably use it myself.
However this is not within the scope of this extension.
Kr
Edward
