### ISSUE TITLE
Bug: filter is reset after opening/closing a workitem

### ISSUE THREAD

**Issue by edtro** [edtro/EdTro.AzureDevOps.Extensions.querybasedboards#43]
As reported on the marketpace, by Janni Kajbrink:

Hi, I really like the feature to filter the task board for different values. But when I have selected a filter and then open for example a User Story and then closes it, the selected filter is cleared.  To reproduce 
1. Select a user in the Assigned To filter 
2. Open a user story
3. Close the user story 
4. The filter is cleared and there is no longer any user selected in the "Assigned to" filter  Is this expected?

**Comment by edtro** [comment]
Resolved in 0.21066

**Comment by jdshkolnik** [comment]
I'm on v0.21067.4 and it's still messed up. The filter disappears. Furthermore, none of the state is remembered at all. I can shift to results or editor, come back, and all the taskboard settings have been reset (filter hidden, etc.)

**Comment by edtro** [comment]
Hi @jdshkolnik 
With the latest release it should be resolved completely (I had stated within the release notes of the previous release that I was still working on this issue). 

But when I read your comments, I think something else is also causing some misunderstandings.

The 'quick filter' is not enabled by default. You can do this within the advanced configurations (and when you do this within the 'global' you can enable it by default for all queries).

When the 'quick filter' is not enabled by default... saving the state and reloading it, wont work eather. So you really have to set like this example:

![image](https://user-images.githubusercontent.com/27762373/110430174-46790a80-80ac-11eb-90c2-6bf81adffec2.png)

**Comment by jdshkolnik** [comment]
@edtro, how did you get to that screen?

**Comment by edtro** [comment]
Within your projectsettings... scroll down to the bottom, to the sections Extensions:
![image](https://user-images.githubusercontent.com/27762373/110484880-5e23b380-80eb-11eb-9824-8de4b51079b3.png)

Or browse to the following url:
{your_org_url/{your_project}/_settings/realdolmen.EdTro-AzureDevOps-Extensions-QueryBasedBoards-Public.EdTro-AzureDevOps-Extensions-QueryBasedBoards.ConfigTab

**Comment by jdshkolnik** [comment]
I plugged the JSON in but no change for me. I also noticed that I get an error flashing quickly when a taskboard is loading (with or without the JSON):

![image](https://user-images.githubusercontent.com/2047520/110495042-218f9200-80c2-11eb-89bb-dd33ff548f83.png)

**Comment by edtro** [comment]
Dear @jdshkolnik 
I am really puzzled by the fact that the menu item is not showing up within the project settings. Even the extension 'Contribution Guide' from Microsoft (a very usefull tool, when you are building extensions) is not showing up in all of the online organizations I have access to. Sometimes there are differences between teamprojects. I think that this is a problem at the end of Microsoft. For on-premises I am not experiencing any problems.

Regarding the error above: your earlier screenshot show a couple of lines. These are configuration that where created for several queries that where used within QBB... so these configs are created.

When you enable 'view all queries', you will see all of the configurations of queries you don't have access to, like queries of other users that are created within 'my queries'.

So security permissions should not be a problem (and the context is handled within the manifest of the extension... when you install the extension you will get a message, what permissions the extension will be granted). 

I am not experiencing / seeing any problems at the moment. 

So again, for the problem above... I will need some more information. Like what type of org (online or onprem/version) and what is displayed within the development console of the browser. 

Kr
Edward

**Comment by edtro** [comment]
Dear @jdshkolnik 
Thank you for your feedback, great to know that your problem with the queries are solved. I couldn't reproduce this at my end. Hopefully this is a one time only incident... but I will be on the watch, to see if it arises again somewhere.

Regarding the project settings, like I said: I am really puzzled. It is also happening for other extensions, so it is a Microsoft problem, but posting a issue on their GitHub repos does not help. I tried for an other issue, but no response whatsoever. I am considering to redesign this and come up with an other solution for this... but at the moment you should use the workaround with the url.

Kr
Edward
