### ISSUE TITLE
Doing Done column doesn't work

### ISSUE THREAD

**Issue by cliveytech** [edtro/EdTro.AzureDevOps.Extensions.querybasedboards#49]
Hi @edtro,
Thanks for implementing this excellent extension.  I've got swimlanes and columns working, but the Doing/Done column doesn't work for me.  If I use the api to query one of our Work Items I can see the Done Column is set as:

"System.BoardColumn":"In Progress","System.BoardColumnDone":true

So I implemented the column as:

 {
         "name":"In Progress",
         "title":"In Progress/Active",
         "width": 2,
         "doingDone":{
            "field":"System.BoardColumnDone",
            "doingTitle":"Working on it...",
            "doingDefaultValue":false,
            "doneTitle":"Finished!",
            "doneValue":true
         }
      },

Which does show the new sub-columns but doesn't show any of the cards in the done column (just in doing).   Is there something I'm doing wrong?

Many thanks
Clive

**Comment by edtro** [comment]
@cliveytech Dear Clive,
Please take a look at this thread: https://github.com/edtro/EdTro.AzureDevOps.Extensions.querybasedboards/issues/41 
The main issue is that the 'System.BoardColumnDone' field is not editable by the api, this is a system field.

You have got two options:
- Create a new Yes/No field and use this within the qbb boards .as the 'done-field' (but this will not reflect within the standard boards). An example is provided within this https://github.com/edtro/EdTro.AzureDevOps.Extensions.querybasedboards/blob/master/public/config.md document.
- Or you can use a NOT SUPPORTED workaround created by me, see also the same document, mentioning "unsupportedAPIFields?: string[]; //like the name suggest: USING THIS IS UNSUPPORTED... try at your own risk. Use the correct fieldnames, like: WEF_{ID-CODE}_Kanban.Column.Done (note: only works when field='System.BoardColumnDone')"... so if you want to use this (you are warned) just add this section and figure out the correct WEF_ field you should use.

Hope this helps.

Kr
Edward
