### ISSUE TITLE
Feature Request: Add ability to set custom Board Columns

### ISSUE THREAD

**Issue by RansomVO** [edtro/EdTro.AzureDevOps.Extensions.querybasedboards#50]
We have a project that is just for doing an extensive platform review. As such, we have:
- renamed a couple of columns _(which show up with the State instead of Column name)_
- Made slight changes to the order of the columns. _(but shows up in original order.)_

It would be really nice to be able to get Show as Board to display like our board.

**Comment by RansomVO** [comment]
Never mind, just figured out how to do the configuration.
Awesome! :)

**Comment by edtro** [comment]
Great to hear!
Kr
Edward

**Comment by awojtas** [comment]
@RansomVO would you mind sharing your configuration? Love to see how to set the custom column order as ours aren't showing up in the order we'd like. Thanks!

**Comment by edtro** [comment]
Hi,

I have this setup:
```
{
   "columns":[
      {
         "name":"New",
         "title":"New/Backlog",
         "isBacklog":true
      },
      {
         "name":"Active",
         "title":"Active/Doing"
      },
      {
         "name":"Resolved",
         "title":"Resolved"
      },
      {
         "name":"Closed",
         "title":"Closed/Done",
         "isBacklog":true
      }
   ]
}
```
  
Result: 
![image](https://github.com/edtro/EdTro.AzureDevOps.Extensions.querybasedboards/assets/27762373/d2875f31-1f48-4aff-8018-509f109cefbf)


And when I change it to:
```
{
   "columns":[
      {
         "name":"Resolved",
         "title":"Resolved"
      },
      {
         "name":"New",
         "title":"New/Backlog",
         "isBacklog":true
      },

      {
         "name":"Active",
         "title":"Active/Doing"
      },

      {
         "name":"Closed",
         "title":"Closed/Done",
         "isBacklog":true
      }
   ]
}
```

This results in:
![image](https://github.com/edtro/EdTro.AzureDevOps.Extensions.querybasedboards/assets/27762373/2b50527f-9516-4c8f-a1b3-d926c7cd427c)


I hope this helps
Kr
Edward
