### ISSUE TITLE
The DateTime Field is displayed wrong when the date is a future date

### ISSUE THREAD

**Issue by jamyzhang** [edtro/EdTro.AzureDevOps.Extensions.querybasedboards#53]
Hi,

Thank you for your great plugin. I want to report a bug that I use the configration to display a future datetime like below:

{
   "fields":[
      {
         "name":"Microsoft.VSTS.Scheduling.TargetDate",
         "title":"TargetDate"
      },
      {
         "name":"Custom.RequestFrom",
         "title":"Requesting Team"
      }
   ]
} 

The value of the field "TargetDate" is the future date time and the it displayed wrong as "Just Now".

![image](https://user-images.githubusercontent.com/4920197/145056149-991cc511-223c-4273-a379-b676fe1582fd.png)

**Comment by edtro** [comment]
Dear @jamyzhang,
Thank you very much for your feedback. Highly appreciated!

I have investigated this and indeed within the 'Ago' component of the Azure DevOps UI library, future dates are displayed as 'Just now'. See: https://developer.microsoft.com/en-us/azure-devops/components/time 

I will fix this. Keep you posted.

Kr
Edward

**Comment by jamyzhang** [comment]
May I know when do you release this fix. Our company is using your plugin and we want this a little urgently.

**Comment by ErkanYardibi** [comment]
Hello. We are also waiting for this fix :-)

Thanks!

**Comment by edtro** [comment]
Dear,
As I have said... I am using the Ago component from the Azure DevOps UI... it is actually a bug within that component, but you have nowhere to report it (and I think it is abandoned).
I am looking at a solution using momentjs, to replace this. 
But Microsoft is making my life as an extension developer very difficult currently, see my replies on their blogpost anouncing an updated interface of the queries/boards: https://devblogs.microsoft.com/devops/azure-boards-ux-modernization-public-preview/#comment-2913
They have introduced a couple of new bugs, but they are not replying to anything :-(
Kr
Edward

**Comment by edtro** [comment]
Dear @jamyzhang  and @ErkanYardibi 
I just released a new version to the marketplace. Please try it out! It should have fixed te problem
Kr
Edward

**Comment by ErkanYardibi** [comment]
Dear Mr.Edward,
Thank you very much! I tried and all problems were solved with your magic touch. Thank you so much!

**Comment by edtro** [comment]
Your welcome!
