### ISSUE TITLE
BUG in NEW UI: It created tabs called "Boards" on the Boards view, with no way to remove or rename these.

### ISSUE THREAD

**Issue by edtro** [edtro/EdTro.AzureDevOps.Extensions.querybasedboards#55]
Currently Microsoft is working on the 'Azure Boards Ux Modernization' and this is currently in public preview (see: https://devblogs.microsoft.com/devops/azure-boards-ux-modernization-public-preview/). I have noticed a couple of bugs within this new preview feature, that has effect on the AzDo extension framework/libraries, that causes this extension not to work as it should. I have already reported the bugs that I have found and I am awaiting a fix for these.

I am doing my best to follow-up on this! Disabling the preview feature should resolve any problems regarding this extension.

**Comment by fforjan** [comment]
@edtro  any update on this problem ? still pending on Microsoft side ?

**Comment by fforjan** [comment]
note, the reason I'm asking is that I've seen this new banner today :
![image](https://user-images.githubusercontent.com/601810/167173953-b30267dc-24e9-4443-a9b1-6de18143e314.png)
Or at least I think it is new...

**Comment by fforjan** [comment]
Thanks for the status !

**Comment by JasperGilhuis** [comment]
Is it a possibility to have the "Boards" integration configurable in the settings of the extension? 
This way you could have the Boards Hub Feature enabled, and use the preview functionality of the extension but not have the "Board" issue? When fixed enabling it would allow for using the boards?

**Comment by fforjan** [comment]
@edtro it seems with the latest iteration I cannot see this anymore.
I may be checking the wrong thing but...

**Comment by edtro** [comment]
This is solved by Microsoft
