### ISSUE TITLE
Settings are not persistent

### ISSUE THREAD

**Issue by SeeDoubleYou** [edtro/EdTro.AzureDevOps.Extensions.querybasedboards#57]
When I show a query as a board I can set settings like "how filter bar" and "show team project". I'd expect these settings to persist, but they do not, I have to set these each time I view the query as a board (also in the event of a reload). It would be great to be able to store these settings.

**Comment by edtro** [comment]
Dear,

Not so long ago I have answered the same question within the Q&A section of the marketplace...

With great pleasure I can confirm that I have implemented an option to do this. Please take a look at the documentation regarding using the 'advanced' configurations, see: https://github.com/edtro/EdTro.AzureDevOps.Extensions.querybasedboards/blob/master/public/config.md
Take a look at the mentions regarding "settings" within the json.

You can set it up for individual queries and globally for all of the queries within the project. You can find the configs within the Project Settings Hub > within the Extensions section (at the left side within the nav pane) > select 'Query Based Boards'.

Hope this helps.
Kr
Edward

**Comment by SeeDoubleYou** [comment]
awesome, thanks!
