### ISSUE TITLE
Failed to parse configuration: 70969eee-bf8f-48d6-a84f-e6d5c732e57a

### ISSUE THREAD

**Issue by ErkanYardibi** [edtro/EdTro.AzureDevOps.Extensions.querybasedboards#58]
Dear Edtro,

Thanks for your effort and solution you provided to us. I have been using the Queryboards because bringing benefits to show the boards in right order of query and style.

The issue I encountered is, when I setup the configuration for queryboards in settings, the filter I wrote properly is saved but "Failed to parse configuration: xxxx" warning is appeared. And the filter is not working. I have some filters working in different queries, but today I started to see this warning. Do you know about any solution?

The filter is like below;

{
"fields":[
{"name":"System.AreaPath","title":"Area","filter":true},
{"name":"System.Tags","title":"Tags","filter": true},
{"name":"System.Parent","title":"Parent"},
{"name":"Microsoft.VSTS.Common.Priority","title":"Priority"},
{"name":"Custom.FirstNotificaitonDate","title":"First Notif.Date"}
{"name":"Custom.FirstResponseDate","title":"First Resp.Date"}
],
"styleRules":[
      {
         "field":"Custom.FirstResponseDate",
         "value":"",
         "color":"#FFA500"       
      },
],
"settings":{"showFilter":true}}

Thanks.

**Comment by edtro** [comment]
Dear,
When I try to parse your JSON file with https://jsonformatter.curiousconcept.com/#
I am getting an error message. Please try to resolve this first. 
Kr
Edward

**Comment by ErkanYardibi** [comment]
Thank you very much,
I didn't know the JSON validation page, and I corrected my mistakes and works well. 
Thanks

**Comment by edtro** [comment]
Thank you for using Query Based Boards and for reaching out :-)
