### ISSUE TITLE
Boards do not respect query filters

### ISSUE THREAD

**Issue by avylove** [edtro/EdTro.AzureDevOps.Extensions.querybasedboards#59]
When you use a "Work items and direct links" query like what's described [here](https://stackoverflow.com/a/45252562), the query seems to be completely ignored.

What I'm specifically looking for is a way to query all the children of a specific type and show them in a board. It seems dropping the parent from the query result may not be possible, but showing everything in a board should be.

**Comment by edtro** [comment]
Dear,
Two things I want to mention:
- Please make sure that you have saved the query... unsaved queries can not be displayed (this is a limitation of the extension framework, just see the tab 'Charts' that has the same issue)
- Only Flat and One-hop queries (and only the parent-child links) are supported

Both prerequisites are also clearly mentioned within the readme on the marketplace. Please check if this is the issue.

I also do not clearly understand what you are trying to achieve. The following query is -I think- the nearest: 
```
SELECT
    [System.Id],
    [System.WorkItemType],
    [System.Title],
    [System.AssignedTo],
    [System.State],
    [System.Tags]
FROM workitemLinks
WHERE
    (
        [Source].[System.TeamProject] = 'Test-QBB-Scrum'
        AND [Source].[System.Id] = 2127
    )
    AND (
        [Target].[System.TeamProject] = 'Test-QBB-Scrum'
        AND [Target].[System.WorkItemType] = 'Bug'
    )
ORDER BY [System.Id]
MODE (MustContain)
```
The board is showing only the bugs for this Feature (the PBI's are filltered), so it is working correctly.... nothing is ignored.

Kr.
Edward

**Comment by edtro** [comment]
Btw. my appologies for my late reply...

**Comment by avylove** [comment]
I hadn't saved it. That was the main issue.
The query above is close to what I'm trying to to do, but it still returns the parent rather than just the children, but I think that's a limitation of ADO rather than the plugin.

**Comment by edtro** [comment]
@avylove 
Thank you for your feedback, highly appreciated 👍
