### ISSUE TITLE
Query & configuration for Feature board

### ISSUE THREAD

**Issue by vensub-fy** [edtro/EdTro.AzureDevOps.Extensions.querybasedboards#60]
I understand your extension is powerful. But I wish you had these as pre-packaged queries.
Can someone share the query and configuration details as to how to get this board in place.

![Screen Shot 2022-05-29 at 8 55 19 PM](https://user-images.githubusercontent.com/61947101/170903539-3c1f439b-6007-4f89-9de9-b70b6b63866c.png)

**Comment by vensub-fy** [comment]
Ok, I think i figured this out. Thanks, this board is very helpful for us.

Here is the query I used.
`select [System.Id], [System.WorkItemType], [System.Title], [System.AssignedTo], [System.State], [System.Tags], [Microsoft.VSTS.Common.Priority] from WorkItemLinks where (Source.[System.TeamProject] = @project and Source.[System.WorkItemType] = 'Feature' and not Source.[System.State] in ('Closed', 'Completed', 'Done')) and (Target.[System.TeamProject] = @project and Target.[System.WorkItemType] in ('Product Backlog Item', 'Bug')) order by [Microsoft.VSTS.Common.Priority], [System.Id] mode (MustContain)`

And I was able to see an option "Show as Taskboard" 
![Screen Shot 2022-05-30 at 9 10 31 AM](https://user-images.githubusercontent.com/61947101/171009729-5945c37b-c7bd-4375-bd96-2e4a80775373.png)

**Comment by edtro** [comment]
Great to hear that you tried it yourself!
To get the most out of the queries itself, try to use the extenion created by Otto Streifel, see: https://marketplace.visualstudio.com/items?itemName=ottostreifel.wiql-editor
