### ISSUE TITLE
Cannot save Global configuration

### ISSUE THREAD

**Issue by lieneth** [edtro/EdTro.AzureDevOps.Extensions.querybasedboards#63]
I get error "Failed to parse configuration: N-E" 
Where I N-E could refer to our project name.
I can see, that it is marked in the fielss ID under settings. 
It does not matter if I try to save empty "Global" configuration or one set up with data, like described in this post: 
https://github.com/edtro/EdTro.AzureDevOps.Extensions.querybasedboards/blob/master/public/config.md
<img width="864" alt="image" src="https://user-images.githubusercontent.com/108413596/178275490-096dd79c-7e25-4510-b02b-142a4eb35d62.png">

**Comment by edtro** [comment]
Hi @lieneth,
Did this resolve the problem? 
Kr
Edward

**Comment by edtro** [comment]
I've tried to save an 'empty' config... and I am also getting an error.
Just try to save this config:
`{}`

PLEASE BE AWARE: when you get an error, please close this errorbox with the 'X'. And (re)save your config.

**Comment by lieneth** [comment]
I did manage to save the query when I removed comments. 
{
    "settings": {
        "showFilter": true
    },
    "fields": [{
            "name": "System.IterationPath",
            "title": "Iteration:"
        }
    ],
    "backlogTabs": [{
            "tabNumber": "1",
            "level": "Epics",
            "teamId": "",
            "queryId": "a544aff3-247b-45cc-bb25-7c152699ccda",
            "title": "Custom Board"
        }, {
            "tabNumber": "1",
            "level": "Features",
            "teamId": "",
            "queryId": "837c4e23-a8e9-43b0-b157-e2860953c882",
            "title": "Custom Board"
        }, {
            "tabNumber": "1",
            "level": "",
            "teamId": "",
            "queryId": "df07e43a-c276-4e69-a3f3-50c89a64c7c5",
            "title": "Custom Board"
        }
    ]
}

**Comment by edtro** [comment]
ok, great!
Sorry but I didn't have the time to create an UI for the config settings.
But just a tip: use the following site https://jsonformatter.curiousconcept.com/ to check if it is a valid json.
Next you can check the console output (within the browsers developers section... F12), to see the error in detail.

I will close this issue.

Kr
Edward
