### ISSUE TITLE
Add the Iterations to the filter and to the Show fields options

### ISSUE THREAD

**Issue by destacey** [edtro/EdTro.AzureDevOps.Extensions.querybasedboards#64]
Great tool.  It would be very helpful if the Iterations were available in the quick filter bar and available to show on the card.

![image](https://user-images.githubusercontent.com/9167606/185218265-3819629b-aa13-45bd-b740-f5cc4c90fa33.png)

Thanks

**Comment by edtro** [comment]
Hi,
You should already be able to do that. Please review this manual: https://github.com/edtro/EdTro.AzureDevOps.Extensions.querybasedboards/blob/master/public/config.md

Kr
Edward
