### ISSUE TITLE
Implementation of TreeView queries

### ISSUE THREAD

**Issue by edtro** [edtro/EdTro.AzureDevOps.Extensions.querybasedboards#69]
Hi All,

I want to inform you that I am in the middle of implementing the 'TreeView' query type. As of yet only the 'Flat' and 'OneHop' query types where supported. 

Before I go any further, I want to note that **ONLY** the 'Parent/Child' type will be implemented.

So how it is going to be:

When you startup your Tree query, you will notice that the "Show As Taskboard" will be shown and when you open it, the first two levels of your tree will be shown as your taskboard, like:

![image](https://user-images.githubusercontent.com/27762373/213634103-bd7d8657-f282-499b-80ad-dbb8c182e697.png)

But you can select the level you want to display, like:
![image](https://user-images.githubusercontent.com/27762373/213635812-07169bbc-b761-4bfc-a1ab-bd2426584b03.png)

When you use the query within the Backlog as a tab, the level selection (and setup) of the backlog is being used, like:
![image](https://user-images.githubusercontent.com/27762373/213636298-0c4d5a86-de49-4898-932a-fc1e658a0094.png)

Btw: I have also added an extra header, so you can see the name of the query and you can jump to the query itself.

I hope this will be helpfull.

Kr.
Edward

**Comment by edtro** [comment]
This item is GA

**Comment by briandye** [comment]
@edtro thanks much for your add-in and the details around this support for Parent/Child TreeView queries. I do notice when I use the "Match linked work items first" filter option, the taskboard says "No Results" even though the query does return results. If I use the "Match top-level work items first" filter option, the taskboard does work, however the query results are not what I would like them to be. Thoughts on if this supported or changes I could make?

![image](https://github.com/edtro/EdTro.AzureDevOps.Extensions.querybasedboards/assets/229137/2349cac3-0273-44dc-96ba-7cff18eb29d7)
