### ISSUE TITLE
Showing parent in field card not working

### ISSUE THREAD

**Issue by nOrphf** [edtro/EdTro.AzureDevOps.Extensions.querybasedboards#70]
Hi

When I add 
`      {
         "name":"System.Parent",
         "title":"Parent"
      }`
To a query configuration I get a blank list in the query-board.

**Comment by edtro** [comment]
dear @nOrphf ,

Please include some more information, like if it is on the Azure DevOps Services (online) or Azure DevOps Server (on-prem + include the version) and the full json used as a config.

If I am using the following config (online), it works:

{
   "settings":{
      "showFilter":true,
      "zoomLevel": 4,
      "showStoryPoints": true,
      "showTags": true
   },
   "fields":[      
      {
         "name":"Custom.Technology",
         "title":"Technology",     
         "filter": true   
      },
      {
         "name":"System.Parent",
         "title":"Parent"
      }
   ],
   "styleRules": [
       {
           "field": "Microsoft.VSTS.Common.Priority",
           "value": "1",
           "color": "#FF0010"
       }
   ]
}

Kr
Edward

**Comment by edtro** [comment]
Closing the issues

**Comment by JamborJan** [comment]
Only FYI: I found that the field System.Parent is only working when using the Azure DevOps cloud service. Using Azure Devops Server will show an error stating: 

```
No results...
Please review the query and/or filter.
```

Testet wiith Azure DevOps Server 2022 and 2020. I'm not sure if there is another field to use or if the internal API is not supporting this field when the on premises server is used.
