### ISSUE TITLE
Feature request: Remove dublicate tasks

### ISSUE THREAD

**Issue by nOrphf** [edtro/EdTro.AzureDevOps.Extensions.querybasedboards#71]
Hi

I use this to find all PBI, tasks and bugs.
The essence of my query is rather simple.
Setting is "Return all top level items" - links only "Childs"

Top level filter is 
Assigned = @me
Work item type IN Product Backlog Item,Task,Bug

Second level filter is:
Work item type IN Task,Bug

This is the closest I have come to get everything which is assigned to me, but if a PBI is assigned to me, and contains a Task which is assigned to my this task shows up as a child link but also as a top level item.

So would it be possible to get QBB to filter out top level items which is also found as child links?

Or add some kind of extra filtering to the query that if a top-level "task" has a parent assigned to "@me" then hide?

Regards Lars

**Comment by edtro** [comment]
Dear,
I am sorry to inform you, that I am not planning to implement a feature like this is any time soon. 
Kr
Edward
