### ISSUE TITLE
Bug: Cards showing "Unassigned" for work items that are assigned

### ISSUE THREAD

**Issue by mvonballmo** [edtro/EdTro.AzureDevOps.Extensions.querybasedboards#73]
**Observed**

Some cards show _Unassigned_ when they are actually assigned. When opened, the work items are actually assigned.

**Expected**

Cards show the actual assignee in all cases.

**Analysis**

I have not been able to determine any pattern to when a card shows unassigned instead of the actual assignee.

- There are direct team members where the assignee is sometimes shown correctly and sometimes not
- There are cards that show indirect team members (e.g. included via a group) correctly
- There are cards that show assignees who are not even team members

So far, it just seems random. Since I can't see the implementation, I can't see how the assignees are chosen, so I can't really narrow the problem down any farther.

**Comment by edtro** [comment]
Dear @mvonballmo 

Sorry to hear that you are running into issues. I am trying my best to be of help.

But I have to say that I have never witnessed such behaviour, while I am using this extension myself extensively. 
And next to this... be aware that there is no auto-refresh implemented, so if someone else modified the item, then you are looking at old data.

What is implemented: really simple... the contents of the field 'System.AssignedTo' should be displayed.

It is easy to track within the devtools of the browser: load your board completely, open up the network tab, clear everything, start a recording session and hit the 'refresh' button from the QBB extension (within the filterbar or custom toolbar at the top left). You will see all of the calls to the REST API. Just review the '_apis/wit/workItems?ids='. You will notice the 'System.AssignedTo' field is included. 

You are able to copy past the request and review it in a browser/rest client.

Kr
Edward

**Comment by mvonballmo** [comment]
@edtro Thanks so much for your quick and detailed reply.

This is truly a game-changer extension and I'd like to thank you for having built it.

I've had a look at the results of the web APIs and can see something interesting is going on with our specific example. Azure is not returning full records for all of the assignees.

This is an example from the data request for work items:

![image](https://user-images.githubusercontent.com/1214927/217473087-4edc233a-4d4b-4fd4-bcee-d877ad7239a5.png)

This is what it looks like in the boards:

![image](https://user-images.githubusercontent.com/1214927/217473253-23b781df-c57d-49a7-96c5-86ee55d4ba8b.png)

Now that I kind of knew what to look for, I was able to search the code in the browser and found my way to "AppBoard.ts", which creates cards, calculating the assignee with the following logic:

![image](https://user-images.githubusercontent.com/1214927/217474628-9c55d3c8-3634-43c3-9156-8805da627d78.png)

So it ends up choosing unassigned, even though there is a display name.

I suppose we could adjust the logic in QBB to do a fuzzy match on all loaded assignees, to "fix up" those assignees which have appeared without an ID. I.e., we could keep a map of display-name-to-assignees and look up in that when creating a card with a mangled assignee. But that only works if the assignee appears in full somewhere else. Otherwise, you'll still have only the mangled assignee in the data and no other data from which to repair it.

So that's not very promising.

The real question is: why is Azure sometimes sending full data for the assignee and sometimes sending just the display name?

Well, it turns out that, when we imported our data from an on-prem Azure DevOps Server to Azure DevOps Services, some of the work items appear to be assigned correctly, but are actually assigned to a phantom-stub user with the correct display name, but nothing else. This is actually a subtle problem in our data that will prevent people from finding all work items assigned to e.g., `@me`. Work items assigned to these phantom stubs simply won't appear in query results.

When I looked more closely at the work item indicated in the screenshots above, I saw that the assignee had a generic icon.

![image](https://user-images.githubusercontent.com/1214927/217478287-640b6d7f-0f81-41fe-bb03-fc9dc840f52c.png)

I simply selected the _same user_ from the assignee list and Azure detected it as a _change_.

![image](https://user-images.githubusercontent.com/1214927/217478528-25fce353-9ed1-4d39-bf99-ee95a28fbb00.png)

When I saved the item and returned to the board, QBB automatically updated the assignee instantly (without an explicit refresh).

Happily for you, it turns out that the problem is in our data.

**Comment by edtro** [comment]
Dear @mvonballmo 
Thank you for your reply.... this really really really made my day :-)
Kr
Edward
