### ISSUE TITLE
Customize dependency arrow direction

### ISSUE THREAD

**Issue by maga-polito** [edtro/EdTro.AzureDevOps.Extensions.querybasedboards#74]
In our team the convention we use to represent predecessor-successor dependency is that successor points to predecessor as it depends from him. 

Currently we have a delivery plan where dependencies are represented in this way so it is confusing to have them in the opposite direction for this board.

Is there a way to change the way dependency arrows are rendered and invert their direction?

**Comment by edtro** [comment]
Dear @maga-polito 

It depends on how you are looking at it... 

Here is an example, showing the states as columns:
![image](https://user-images.githubusercontent.com/27762373/222955847-1a1a09e8-e642-44b5-985d-c0306159ccf4.png)

The dependency arrows appear to point the wrong way (backwards)... but when you view the board as a default kanban board, with states as column, the columns do not visualize a timeline.

When you do visualize the columns to resemble a timeline, like so:
![image](https://user-images.githubusercontent.com/27762373/222956053-51bde6ee-d947-4c1d-9f6d-40e5e082d6ef.png)

Then you will notice that the arrows are visualized correctly.

Kr.
Edward
