### ISSUE TITLE
Show the number of Items in a board column

### ISSUE THREAD

**Issue by osommer2091** [edtro/EdTro.AzureDevOps.Extensions.querybasedboards#77]
It would be great to just see the number of items in a column, in order to get a hand of the work load. Afterwards the WIP limits could be transferred.

**Comment by edtro** [comment]
Hi,

When you active the wiplimit, like:
```
{
   "columns":[
      {
         "name":"New",
         "title":"New/Backlog",
         "isBacklog":true
      },
      {
         "name":"Active",
         "title":"Active/Doing",
         "wipLimit": 5
      },
      {
         "name":"Resolved",
         "title":"Resolved",
         "wipLimit": 5
      },
      {
         "name":"Closed",
         "title":"Closed/Done",
         "isBacklog":true
      }
   ]
}
```
You will see the number of items in a column... please note: //backlog=false && if >= 0 then count and limit will be displayed 

Hope this helps.
Kr
Edward

**Comment by osommer2091** [comment]
@edtro thank you for the swift answer! However, since I'm a regular user and not a developer, I don't know what to do with the snippet you gave. Could you explain further how to proceed?

**Comment by edtro** [comment]
@osommer2091 Hi, please goto your Project Settings, within the menu > scroll down to Extensions, select Query Based Boards. Next step is to select your query and add the JSON config and hit the Save button. 

Please review this page: https://github.com/edtro/EdTro.AzureDevOps.Extensions.querybasedboards/blob/master/public/config.md

Tips:
- Open up the developer console of your browser (F12) and review the logs while saving the config
- Use a JSON formatter (online)

Unfortunately I haven't implemented an user friendly UI to configure these advanced settings

Kr
Edward
