### ISSUE TITLE
Please allow an option to add more fields for "Show as board" cards

### ISSUE THREAD

**Issue by Chana823** [edtro/EdTro.AzureDevOps.Extensions.querybasedboards#83]
Hi we have queries created for customised identity fields on Azure WIs and I would like to know how to add more fields to the cards in board view under queried data. By default it only shows the title and the assigned to fields of a work item.

![Screenshot 2024-02-02 161410](https://github.com/edtro/EdTro.AzureDevOps.Extensions.querybasedboards/assets/73467763/109c8ca9-13c5-4b45-b5f3-ff6e6532539f)

**Comment by edtro** [comment]
Dear @Chana823, this perfectly possible. See the [manual](https://github.com/edtro/EdTro.AzureDevOps.Extensions.querybasedboards/blob/master/public/config.md) how to do it.
Please note: not all the fieldtypes (like identity) are supported.

Kr
Edward
