### ISSUE TITLE
Feature Request: Quick Add Task in the Board View

### ISSUE THREAD

**Issue by johnnylamxyz** [edtro/EdTro.AzureDevOps.Extensions.querybasedboards#84]
The extension works great and is just what my team needed. Much appreciation to the developers.

In the Boards already in ADO, each work item has the "more options" button, dropping down a list of options, including a quick "add task" option.

![Screenshot 2024-02-09 125909](https://github.com/edtro/EdTro.AzureDevOps.Extensions.querybasedboards/assets/150955700/b5b3266e-fbe4-40e7-b8dd-df324fe104eb)

Adding this feature to the extension would allow the user to quickly add a task to a story without having to exit the board view.

**Comment by edtro** [comment]
Dear @johnnylamxyz unfortunately I am not planning to implement a feature like this as of yet. 
For the time being I will close this issue..
Kr.
Edward
